services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.development
    volumes:
      - ./frontend:/app
      - /app/node_modules # Avoid overriding node_modules
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.development
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules  # Avoid overriding node_modules